### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by aquiurbex** [BenCodez/VotifierPlus#32]
Hello, my VotifierPlus dident work an show this error: 
[VotifierPlus]: Failed to send vote to survival(127.0.0.1:0): Vote (from:minestatus.net test vote username:aquiurbex address:84.78.240.192 timeStamp:1672358812821), ignore this if server is offline

My bungeecord config:

```
Debug: false
host: 0.0.0.0
port: 25864
Forwarding:
  survival:
    Enabled: true
    Host: '127.0.0.1'
    Port: '25891'
    Key: '(Survival public key)'
```
    
   
My survival config:
```

DebugLevel: NONE
host: 0.0.0.0
port: 25891
Forwarding:
  survival:
    Enabled: false
    Host: ''
    Port: ''
    Key: ''
```
    
  
    
Thanks for reading.
